import type { FoodItem, FoodCategory } from "~/types/nutrition";

// Per-100 g seed data, keto + PDAC oriented. Values are conservative
// USDA / AusFoodComp averages, rounded to 1 decimal. Fibre / sugar
// alcohols are explicit so net_carbs is computed once at seed time
// and never drifts.
//
// Curation principles:
// - Foundation: pasture-raised animal foods, fatty fish, olive oil,
//   non-starchy veg, dairy fats. The PDAC patient needs energy density
//   without carb load.
// - Easy-digest flag: soft, low-residue, low-FODMAP-friendly, gentle
//   on a chemo-irritated GI.
// - High-fat-PERT flag: triggers the picker prompt about Creon. We're
//   conservative — anything ≥ 15 g fat per typical serving lights up.
// - Avoid: refined sugar, ultra-processed carbs, sugary drinks. We
//   include a few of these (rice, bread) so the patient can log
//   accurately when family meals include them, but they're flagged
//   "high-carb".

type Seed = Omit<FoodItem, "id" | "net_carbs_g" | "created_at" | "updated_at">;

export const SEED_FOODS: Seed[] = [
  // ---------- Protein: meats and poultry ----------
  cat("protein", {
    name: "Chicken thigh, skin-on, roasted",
    name_zh: "带皮烤鸡腿肉",
    emoji: "🍗",
    default_serving_g: 120,
    default_serving_label: "1 thigh (~120 g)",
    calories: 247,
    protein_g: 25.9,
    fat_g: 15.5,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_high_fat_pert: true,
    pdac_notes:
      "Excellent protein. Skin adds fat — take PERT with the meal.",
    pdac_notes_zh: "优质蛋白。带皮脂肪较多 — 进餐时服用胰酶。",
    tags: ["high-protein", "warm", "easy-digest"],
  }),
  cat("protein", {
    name: "Chicken breast, poached",
    name_zh: "白切鸡胸",
    emoji: "🐔",
    default_serving_g: 100,
    default_serving_label: "Palm-sized piece (~100 g)",
    calories: 165,
    protein_g: 31,
    fat_g: 3.6,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Lean — pair with olive oil or avocado for satiety.",
    pdac_notes_zh: "瘦肉 — 配橄榄油或牛油果增加饱腹感。",
    tags: ["high-protein", "lean", "low-fat"],
  }),
  cat("protein", {
    name: "Beef mince, pan-fried (15% fat)",
    name_zh: "煎牛肉碎",
    emoji: "🥩",
    default_serving_g: 100,
    default_serving_label: "Small bowl (~100 g)",
    calories: 250,
    protein_g: 26,
    fat_g: 17,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_high_fat_pert: true,
    pdac_notes: "Iron-rich. Take PERT.",
    pdac_notes_zh: "富含铁质。请服用胰酶。",
    tags: ["high-protein", "iron", "warm"],
  }),
  cat("protein", {
    name: "Pork belly, braised",
    name_zh: "红烧五花肉",
    emoji: "🥓",
    default_serving_g: 80,
    default_serving_label: "2–3 slices (~80 g)",
    calories: 518,
    protein_g: 9.3,
    fat_g: 53,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: false,
    pdac_high_fat_pert: true,
    pdac_notes:
      "Very fatty — small portion + PERT. Watch for steatorrhoea.",
    pdac_notes_zh: "脂肪很高 — 少量 + 胰酶。注意脂肪泻。",
    tags: ["high-fat", "rich"],
  }),
  cat("protein", {
    name: "Salmon, baked",
    name_zh: "烤三文鱼",
    emoji: "🐟",
    default_serving_g: 130,
    default_serving_label: "1 fillet (~130 g)",
    calories: 208,
    protein_g: 22,
    fat_g: 13,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_high_fat_pert: true,
    pdac_notes:
      "Omega-3 rich, anti-inflammatory. Take PERT with this meal.",
    pdac_notes_zh: "富含 Omega-3，抗炎。配胰酶。",
    tags: ["fatty-fish", "omega-3", "high-protein"],
  }),
  cat("protein", {
    name: "Sardines, in olive oil",
    name_zh: "橄榄油沙丁鱼",
    emoji: "🐟",
    default_serving_g: 90,
    default_serving_label: "1 small tin (~90 g drained)",
    calories: 208,
    protein_g: 24.6,
    fat_g: 11.4,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_high_fat_pert: true,
    pdac_notes:
      "Cheap, shelf-stable, calcium + omega-3. Excellent low-appetite option.",
    pdac_notes_zh: "便宜、易储存、富含钙和 Omega-3。食欲不好时的好选择。",
    tags: ["fatty-fish", "shelf-stable", "calcium"],
  }),
  cat("protein", {
    name: "White fish (cod), steamed",
    name_zh: "清蒸鳕鱼",
    emoji: "🐟",
    default_serving_g: 130,
    default_serving_label: "1 fillet (~130 g)",
    calories: 105,
    protein_g: 23,
    fat_g: 0.9,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Very gentle on the gut. Add olive oil for energy.",
    pdac_notes_zh: "对肠胃非常温和。可加橄榄油补充能量。",
    tags: ["lean-fish", "easy-digest", "low-fat"],
  }),
  cat("protein", {
    name: "Egg, whole, boiled",
    name_zh: "煮鸡蛋",
    emoji: "🥚",
    default_serving_g: 50,
    default_serving_label: "1 medium egg (~50 g)",
    calories: 155,
    protein_g: 13,
    fat_g: 11,
    carbs_total_g: 1.1,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Complete protein, easy to digest, cheap calorie boost.",
    pdac_notes_zh: "完整蛋白，易消化，便宜的能量来源。",
    tags: ["high-protein", "complete-protein", "easy-digest"],
  }),
  cat("protein", {
    name: "Tofu, firm",
    name_zh: "老豆腐",
    emoji: "🥘",
    default_serving_g: 100,
    default_serving_label: "Palm-sized block (~100 g)",
    calories: 144,
    protein_g: 17,
    fat_g: 8.7,
    carbs_total_g: 2.8,
    fiber_g: 2.3,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Plant protein, gentle. Soft tofu even gentler.",
    pdac_notes_zh: "植物蛋白，温和。嫩豆腐更易消化。",
    tags: ["plant-protein", "soft", "easy-digest"],
  }),
  cat("protein", {
    name: "Greek yoghurt, full-fat",
    name_zh: "全脂希腊酸奶",
    emoji: "🥛",
    default_serving_g: 170,
    default_serving_label: "1 small tub (~170 g)",
    calories: 97,
    protein_g: 9,
    fat_g: 5,
    carbs_total_g: 3.6,
    fiber_g: 0,
    sugar_g: 3.2,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Probiotic, high satiety, ideal mid-morning protein top-up.",
    pdac_notes_zh: "含益生菌，饱腹感强，上午加餐的好选择。",
    tags: ["high-protein", "probiotic", "easy-digest"],
  }),

  // ---------- Dairy & cheese ----------
  cat("dairy", {
    name: "Cheddar cheese",
    name_zh: "切达奶酪",
    emoji: "🧀",
    default_serving_g: 30,
    default_serving_label: "1 thumb (~30 g)",
    calories: 403,
    protein_g: 25,
    fat_g: 33,
    carbs_total_g: 1.3,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_high_fat_pert: false,
    pdac_notes: "Energy-dense snack. Small portions per meal.",
    pdac_notes_zh: "能量密度高的零食，每餐少量。",
    tags: ["high-fat", "calcium", "snackable"],
  }),
  cat("dairy", {
    name: "Butter, unsalted",
    name_zh: "无盐黄油",
    emoji: "🧈",
    default_serving_g: 15,
    default_serving_label: "1 tbsp (~15 g)",
    calories: 717,
    protein_g: 0.9,
    fat_g: 81,
    carbs_total_g: 0.1,
    fiber_g: 0,
    keto_friendly: true,
    pdac_high_fat_pert: false,
    pdac_notes: "Use for energy density. PERT if cooking eggs/veg in lots of it.",
    pdac_notes_zh: "用于增加能量密度。大量使用时配胰酶。",
    tags: ["fat", "cooking"],
  }),
  cat("dairy", {
    name: "Whole milk",
    name_zh: "全脂牛奶",
    emoji: "🥛",
    default_serving_g: 250,
    default_serving_label: "1 glass (~250 ml)",
    calories: 61,
    protein_g: 3.2,
    fat_g: 3.3,
    carbs_total_g: 4.8,
    fiber_g: 0,
    sugar_g: 4.8,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes:
      "Lactose may worsen diarrhoea during chemo — try lactose-free if so.",
    pdac_notes_zh: "化疗期间乳糖可能加重腹泻 — 必要时改无乳糖牛奶。",
    tags: ["lactose"],
  }),

  // ---------- Fats and oils ----------
  cat("fat_oil", {
    name: "Olive oil, extra-virgin",
    name_zh: "特级初榨橄榄油",
    emoji: "🫒",
    default_serving_g: 14,
    default_serving_label: "1 tbsp (~14 g)",
    calories: 884,
    protein_g: 0,
    fat_g: 100,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_high_fat_pert: false,
    pdac_notes:
      "MUFA, anti-inflammatory. Drizzle on cooked food rather than frying hot.",
    pdac_notes_zh: "单不饱和脂肪，抗炎。最好淋在熟食上而非高温煎炸。",
    tags: ["good-fat", "MUFA", "cooking"],
  }),
  cat("fat_oil", {
    name: "Avocado",
    name_zh: "牛油果",
    emoji: "🥑",
    default_serving_g: 100,
    default_serving_label: "Half avocado (~100 g)",
    calories: 160,
    protein_g: 2,
    fat_g: 14.7,
    carbs_total_g: 8.5,
    fiber_g: 6.7,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes:
      "Fat + fibre + potassium. Excellent for low-appetite days.",
    pdac_notes_zh: "脂肪、纤维、钾元素丰富。食欲不振时的好选择。",
    tags: ["good-fat", "fibre", "potassium"],
  }),
  cat("fat_oil", {
    name: "MCT oil",
    name_zh: "MCT 油",
    default_serving_g: 14,
    default_serving_label: "1 tbsp (~14 g)",
    calories: 855,
    protein_g: 0,
    fat_g: 100,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_notes:
      "Bypasses PERT requirement. Useful when steatorrhoea limits LCT fats.",
    pdac_notes_zh: "可绕过胰酶需求。脂肪泻严重时是好的脂肪替代。",
    tags: ["good-fat", "MCT", "easy-absorb"],
  }),

  // ---------- Vegetables ----------
  cat("vegetable", {
    name: "Spinach, cooked",
    name_zh: "炒菠菜",
    emoji: "🥬",
    default_serving_g: 100,
    default_serving_label: "1 cup cooked (~100 g)",
    calories: 23,
    protein_g: 3,
    fat_g: 0.4,
    carbs_total_g: 3.8,
    fiber_g: 2.4,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Iron, folate, gentle when wilted.",
    pdac_notes_zh: "富含铁和叶酸，焯熟后温和。",
    tags: ["leafy-green", "iron", "low-carb"],
  }),
  cat("vegetable", {
    name: "Bok choy, sautéed",
    name_zh: "炒小白菜",
    emoji: "🥬",
    default_serving_g: 100,
    default_serving_label: "1 cup (~100 g)",
    calories: 13,
    protein_g: 1.5,
    fat_g: 0.2,
    carbs_total_g: 2.2,
    fiber_g: 1,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Familiar, gentle, well-tolerated.",
    pdac_notes_zh: "家常菜、温和、易耐受。",
    tags: ["leafy-green", "low-carb"],
  }),
  cat("vegetable", {
    name: "Broccoli, steamed",
    name_zh: "蒸西兰花",
    emoji: "🥦",
    default_serving_g: 100,
    default_serving_label: "1 cup (~100 g)",
    calories: 35,
    protein_g: 2.4,
    fat_g: 0.4,
    carbs_total_g: 7.2,
    fiber_g: 3.3,
    keto_friendly: true,
    pdac_easy_digest: false,
    pdac_notes:
      "Sulforaphane is good — but raw broccoli can be gassy on chemo days.",
    pdac_notes_zh: "含萝卜硫素 — 化疗期生吃易胀气，建议蒸熟。",
    tags: ["cruciferous", "fibre", "low-carb"],
  }),
  cat("vegetable", {
    name: "Cucumber",
    name_zh: "黄瓜",
    emoji: "🥒",
    default_serving_g: 100,
    default_serving_label: "Half cucumber (~100 g)",
    calories: 16,
    protein_g: 0.7,
    fat_g: 0.1,
    carbs_total_g: 3.6,
    fiber_g: 0.5,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Hydrating, gentle, palatable on nausea days.",
    pdac_notes_zh: "补水、温和、恶心时易接受。",
    tags: ["hydrating", "low-carb"],
  }),
  cat("vegetable", {
    name: "Zucchini, sautéed",
    name_zh: "炒西葫芦",
    emoji: "🥒",
    default_serving_g: 100,
    default_serving_label: "1 cup (~100 g)",
    calories: 17,
    protein_g: 1.2,
    fat_g: 0.3,
    carbs_total_g: 3.1,
    fiber_g: 1,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Bland, soft — useful when appetite is low.",
    pdac_notes_zh: "清淡软糯 — 食欲差时的好选择。",
    tags: ["soft", "low-carb"],
  }),
  cat("vegetable", {
    name: "Cauliflower rice, sautéed",
    name_zh: "花椰菜饭",
    emoji: "🥦",
    default_serving_g: 100,
    default_serving_label: "1 cup (~100 g)",
    calories: 25,
    protein_g: 2,
    fat_g: 0.3,
    carbs_total_g: 5,
    fiber_g: 2,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Rice substitute. Excellent when rice carb load is too high.",
    pdac_notes_zh: "米饭替代品。需要控碳时是不错的选择。",
    tags: ["rice-swap", "low-carb"],
  }),

  // ---------- Fruits (small set, low-sugar end) ----------
  cat("fruit", {
    name: "Berries, mixed",
    name_zh: "什锦浆果",
    emoji: "🫐",
    default_serving_g: 100,
    default_serving_label: "Small bowl (~100 g)",
    calories: 50,
    protein_g: 1,
    fat_g: 0.4,
    carbs_total_g: 12,
    fiber_g: 4.5,
    sugar_g: 6,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Lowest-sugar fruit. Antioxidants. Pair with yoghurt.",
    pdac_notes_zh: "含糖最低的水果之一，抗氧化。配酸奶。",
    tags: ["antioxidant", "low-sugar-fruit"],
  }),
  cat("fruit", {
    name: "Apple, with skin",
    name_zh: "带皮苹果",
    emoji: "🍎",
    default_serving_g: 180,
    default_serving_label: "1 medium (~180 g)",
    calories: 52,
    protein_g: 0.3,
    fat_g: 0.2,
    carbs_total_g: 14,
    fiber_g: 2.4,
    sugar_g: 10.4,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes: "Moderate carbs. Half an apple is plenty mid-afternoon.",
    pdac_notes_zh: "碳水适中，下午吃半个就够。",
    tags: ["fibre", "moderate-carb"],
  }),
  cat("fruit", {
    name: "Banana",
    name_zh: "香蕉",
    emoji: "🍌",
    default_serving_g: 120,
    default_serving_label: "1 medium (~120 g)",
    calories: 89,
    protein_g: 1.1,
    fat_g: 0.3,
    carbs_total_g: 23,
    fiber_g: 2.6,
    sugar_g: 12,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes:
      "Useful for diarrhoea (BRAT) and low energy — but high carb load.",
    pdac_notes_zh: "腹泻或乏力时有用 (BRAT)，但碳水偏高。",
    tags: ["BRAT", "potassium", "high-carb"],
  }),

  // ---------- Grains & starches ----------
  cat("grain_starch", {
    name: "White rice, cooked",
    name_zh: "白米饭",
    emoji: "🍚",
    default_serving_g: 150,
    default_serving_label: "1 small bowl (~150 g)",
    calories: 130,
    protein_g: 2.7,
    fat_g: 0.3,
    carbs_total_g: 28,
    fiber_g: 0.4,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes:
      "Easy to digest but very high carb load. Half a bowl is plenty.",
    pdac_notes_zh: "易消化但碳水很高。半碗即可。",
    tags: ["high-carb", "easy-digest"],
  }),
  cat("grain_starch", {
    name: "Rice congee (plain)",
    name_zh: "白粥",
    emoji: "🍚",
    default_serving_g: 250,
    default_serving_label: "1 bowl (~250 g)",
    calories: 30,
    protein_g: 0.6,
    fat_g: 0.1,
    carbs_total_g: 6.6,
    fiber_g: 0.1,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes:
      "Very gentle. Useful on nausea / mucositis days when nothing else stays down.",
    pdac_notes_zh: "极温和。恶心或口腔溃疡严重时的好选择。",
    tags: ["liquid-meal", "easy-digest", "comfort"],
  }),
  cat("grain_starch", {
    name: "Sweet potato, baked",
    name_zh: "烤红薯",
    emoji: "🍠",
    default_serving_g: 150,
    default_serving_label: "1 small (~150 g)",
    calories: 90,
    protein_g: 2,
    fat_g: 0.1,
    carbs_total_g: 21,
    fiber_g: 3.3,
    sugar_g: 6.8,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes: "Better than rice for fibre + beta-carotene. Still high carb.",
    pdac_notes_zh: "比米饭含纤维和胡萝卜素更多，但仍是高碳水。",
    tags: ["high-carb", "fibre"],
  }),

  // ---------- Nuts & seeds ----------
  cat("nut_seed", {
    name: "Almonds, raw",
    name_zh: "生杏仁",
    emoji: "🥜",
    default_serving_g: 28,
    default_serving_label: "Small handful (~28 g)",
    calories: 579,
    protein_g: 21,
    fat_g: 50,
    carbs_total_g: 22,
    fiber_g: 12.5,
    keto_friendly: true,
    pdac_easy_digest: false,
    pdac_high_fat_pert: false,
    pdac_notes: "Snack-able. Whole almonds may be tough on a chemo gut — try almond butter.",
    pdac_notes_zh: "易作为零食。化疗肠胃敏感时改用杏仁酱。",
    tags: ["nut", "snackable", "good-fat"],
  }),
  cat("nut_seed", {
    name: "Walnuts",
    name_zh: "核桃",
    emoji: "🥜",
    default_serving_g: 28,
    default_serving_label: "Small handful (~28 g)",
    calories: 654,
    protein_g: 15,
    fat_g: 65,
    carbs_total_g: 14,
    fiber_g: 6.7,
    keto_friendly: true,
    pdac_high_fat_pert: false,
    pdac_notes: "Plant omega-3. Best chopped over yoghurt or salad.",
    pdac_notes_zh: "植物 Omega-3 来源。剁碎拌酸奶或沙拉最好。",
    tags: ["nut", "omega-3", "good-fat"],
  }),
  cat("nut_seed", {
    name: "Chia seeds",
    name_zh: "奇亚籽",
    default_serving_g: 15,
    default_serving_label: "1 tbsp (~15 g)",
    calories: 486,
    protein_g: 17,
    fat_g: 31,
    carbs_total_g: 42,
    fiber_g: 34,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes:
      "Almost all carbs are fibre — net carbs ~8 g. Great soaked in milk.",
    pdac_notes_zh: "碳水几乎都是纤维，净碳水约 8 g。泡在牛奶里很好吃。",
    tags: ["fibre", "omega-3", "low-net-carb"],
  }),

  // ---------- Beverages ----------
  cat("beverage", {
    name: "Bone broth",
    name_zh: "骨头汤",
    emoji: "🍲",
    default_serving_g: 250,
    default_serving_label: "1 mug (~250 ml)",
    calories: 30,
    protein_g: 6,
    fat_g: 1,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes:
      "Hydrating + electrolytes + collagen. Excellent on poor-appetite days.",
    pdac_notes_zh: "补水、电解质、胶原蛋白。食欲不振时极佳。",
    tags: ["hydrating", "electrolytes", "comfort"],
  }),
  cat("beverage", {
    name: "Green tea, plain",
    name_zh: "清茶 / 绿茶",
    emoji: "🍵",
    default_serving_g: 250,
    default_serving_label: "1 cup (~250 ml)",
    calories: 1,
    protein_g: 0,
    fat_g: 0,
    carbs_total_g: 0,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Hydrating, mild antioxidant. Avoid late if affecting sleep.",
    pdac_notes_zh: "补水，温和抗氧化。睡眠差则避免太晚饮用。",
    tags: ["hydrating", "antioxidant"],
  }),

  // ---------- Supplements & nutritional drinks ----------
  cat("supplement", {
    name: "Whey protein isolate (1 scoop)",
    name_zh: "乳清蛋白粉 (1 勺)",
    default_serving_g: 30,
    default_serving_label: "1 scoop (~30 g)",
    calories: 380,
    protein_g: 90,
    fat_g: 1,
    carbs_total_g: 3,
    fiber_g: 0,
    sugar_g: 1,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes:
      "Easy way to add 25–30 g protein. Mix with full-fat milk for calories.",
    pdac_notes_zh: "快速补充 25–30 g 蛋白。配全脂牛奶提供能量。",
    tags: ["high-protein", "easy", "supplement"],
  }),
  cat("supplement", {
    name: "Ensure Plus / Fortisip (vanilla)",
    name_zh: "营养补充饮品 (Ensure Plus / Fortisip)",
    default_serving_g: 220,
    default_serving_label: "1 bottle (~220 ml)",
    calories: 150,
    protein_g: 6,
    fat_g: 5,
    carbs_total_g: 20,
    fiber_g: 0,
    sugar_g: 13,
    keto_friendly: false,
    pdac_easy_digest: true,
    pdac_notes:
      "Useful when solid food is hard. High sugar — ration during good-appetite days.",
    pdac_notes_zh: "进固体食物困难时有用。含糖较高 — 食欲好时不必常用。",
    tags: ["liquid-cal", "convenient", "high-carb"],
  }),

  // ---------- Prepared / common dishes ----------
  cat("prepared_meal", {
    name: "Steamed egg custard (savoury)",
    name_zh: "蒸蛋羹",
    emoji: "🍳",
    default_serving_g: 200,
    default_serving_label: "1 bowl (~200 g)",
    calories: 95,
    protein_g: 8,
    fat_g: 6,
    carbs_total_g: 1,
    fiber_g: 0,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes: "Soft, warm, gentle on a sore mouth or queasy day.",
    pdac_notes_zh: "柔软温热，口腔溃疡或恶心时易入口。",
    tags: ["soft", "easy-digest", "high-protein"],
  }),
  cat("prepared_meal", {
    name: "Chicken & vegetable soup",
    name_zh: "鸡肉蔬菜汤",
    emoji: "🍜",
    default_serving_g: 350,
    default_serving_label: "1 bowl (~350 ml)",
    calories: 60,
    protein_g: 5,
    fat_g: 2,
    carbs_total_g: 5,
    fiber_g: 1,
    keto_friendly: true,
    pdac_easy_digest: true,
    pdac_notes:
      "Hydrating + protein + electrolytes. Add olive oil for energy density.",
    pdac_notes_zh: "补水、蛋白、电解质。加橄榄油提高能量密度。",
    tags: ["soup", "hydrating", "comfort"],
  }),

  // ---------- Sweets / things to log honestly but eat sparingly ----------
  cat("sweet", {
    name: "Dark chocolate, 85%",
    name_zh: "85% 黑巧克力",
    emoji: "🍫",
    default_serving_g: 20,
    default_serving_label: "2 squares (~20 g)",
    calories: 600,
    protein_g: 8,
    fat_g: 50,
    carbs_total_g: 22,
    fiber_g: 11,
    sugar_g: 7,
    keto_friendly: true,
    pdac_high_fat_pert: false,
    pdac_notes: "Small square is fine. Magnesium + flavanols.",
    pdac_notes_zh: "一小块即可。富含镁和黄酮。",
    tags: ["treat", "magnesium"],
  }),
];

function cat(category: FoodCategory, partial: Omit<Seed, "category" | "source">): Seed {
  return {
    ...partial,
    category,
    source: "seed",
  };
}
