import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="flex h-full w-full flex-col border-x border-slate-400 md:max-w-2xl">
          <div className="flex flex-row  justify-between border-x border-b border-slate-400">
            <></>
            <h1>My application</h1>
          </div>
          <div className="flex flex-col"></div>
        </div>
      </main>
    </>
  );
};

export default Home;
