"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useLiveQuery } from "dexie-react-hooks";
import { db } from "~/lib/db/dexie";
import { PageHeader } from "~/components/ui/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Button } from "~/components/ui/button";
import { PillarTile } from "~/components/assessment/pillar-card";
import { useLocale } from "~/hooks/use-translate";
import { formatDate } from "~/lib/utils/date";
import { testById } from "~/lib/assessment/catalog";

export default function ViewAssessmentPage() {
  const locale = useLocale();
  const params = useParams<{ id: string }>();
  const id = Number(params?.id);
  const a = useLiveQuery(
    () => (Number.isFinite(id) ? db.comprehensive_assessments.get(id) : undefined),
    [id],
  );

  if (!a) {
    return <div className="p-6 text-sm text-slate-500">Loading…</div>;
  }

  const scores = [
    { label: locale === "zh" ? "功能" : "Function", v: a.functional_score },
    { label: locale === "zh" ? "症状" : "Symptoms", v: a.symptom_score },
    { label: locale === "zh" ? "毒性" : "Toxicity", v: a.toxicity_score },
    { label: locale === "zh" ? "心理" : "Mental", v: a.mental_score },
    { label: locale === "zh" ? "灵性" : "Spiritual", v: a.spiritual_score },
  ];

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-4 md:p-8">
      <PageHeader
        title={`${locale === "zh" ? "评估" : "Assessment"} · ${formatDate(a.assessment_date, locale)}`}
        subtitle={a.trigger === "baseline" ? (locale === "zh" ? "基线" : "Baseline") : a.trigger}
        action={
          <Link href="/assessment">
            <Button variant="secondary">
              {locale === "zh" ? "返回" : "Back"}
            </Button>
          </Link>
        }
      />

      {typeof a.anchor_index === "number" && (
        <Card>
          <CardHeader>
            <CardTitle>Anchor Index</CardTitle>
            <div className="mt-1 text-sm text-slate-500">
              {locale === "zh"
                ? "加权合成分。功能权重最高。"
                : "Function-weighted composite across all five pillars."}
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-5xl font-semibold tabular-nums">
              {a.anchor_index}
              <span className="ml-2 text-lg font-normal text-slate-500">
                / 100
              </span>
            </div>
            <div className="mt-4 grid gap-3 sm:grid-cols-2 md:grid-cols-3">
              {scores.map((s) =>
                typeof s.v === "number" ? (
                  <PillarTile key={s.label} label={s.label} score={s.v} />
                ) : null,
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {(a.ai_summary_patient || a.ai_summary_clinician) && (
        <Card>
          <CardHeader>
            <CardTitle>{locale === "zh" ? "AI 概要" : "AI summary"}</CardTitle>
            <div className="mt-1 text-xs text-slate-500">
              {locale === "zh" ? "由 " : "Generated by "}
              {a.ai_summary_model ?? "Claude"}
            </div>
          </CardHeader>
          <CardContent className="space-y-4 text-sm">
            {a.ai_summary_patient && (
              <div>
                <div className="text-xs font-medium uppercase tracking-wide text-slate-500">
                  {locale === "zh" ? "给患者" : "For the patient"}
                </div>
                <p className="mt-1 whitespace-pre-line">{a.ai_summary_patient}</p>
              </div>
            )}
            {a.ai_summary_clinician && (
              <div>
                <div className="text-xs font-medium uppercase tracking-wide text-slate-500">
                  {locale === "zh" ? "给医师" : "For the clinician"}
                </div>
                <p className="mt-1 whitespace-pre-line">{a.ai_summary_clinician}</p>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>
            {locale === "zh" ? "测试覆盖" : "Tests covered"}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-1 text-sm">
            {(a.tests_included ?? []).map((id) => {
              const def = testById(id as never);
              if (!def) return null;
              const done = (a.tests_completed ?? []).includes(id);
              return (
                <li key={id} className="flex items-center justify-between">
                  <span>{def.title[locale]}</span>
                  <span
                    className={
                      done
                        ? "text-xs text-emerald-600 dark:text-emerald-400"
                        : "text-xs text-amber-600 dark:text-amber-400"
                    }
                  >
                    {done
                      ? locale === "zh"
                        ? "完成"
                        : "complete"
                      : locale === "zh"
                        ? "跳过"
                        : "skipped"}
                  </span>
                </li>
              );
            })}
          </ul>
        </CardContent>
      </Card>

      {a.values_statement && (
        <Card>
          <CardHeader>
            <CardTitle>{locale === "zh" ? "价值观" : "Values"}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="whitespace-pre-line text-sm">{a.values_statement}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
